import { writable } from "svelte/store";

export const 変更 = writable("");
export const テキスト = writable("");
export const 月第1 = writable("");
export const 月第2 = writable("");
export const 月第3 = writable("");
export const 火第1 = writable("");
export const 火第2 = writable("");
export const 火第3 = writable("");
export const 水第1 = writable("");
export const 水第2 = writable("");
export const 水第3 = writable("");
export const 木第1 = writable("");
export const 木第2 = writable("");
export const 木第3 = writable("");
export const 金第1 = writable("");
export const 金第2 = writable("");
export const 金第3 = writable("");

export const 変更IsValid = writable(false);
export const テキストIsValid = writable(false);
export const 月第1IsValid = writable(false);
export const 月第2IsValid = writable(false);
export const 月第3IsValid = writable(false);
export const 火第1IsValid = writable(false);
export const 火第2IsValid = writable(false);
export const 火第3IsValid = writable(false);
export const 水第1IsValid = writable(false);
export const 水第2IsValid = writable(false);
export const 水第3IsValid = writable(false);
export const 木第1IsValid = writable(false);
export const 木第2IsValid = writable(false);
export const 木第3IsValid = writable(false);
export const 金第1IsValid = writable(false);
export const 金第2IsValid = writable(false);
export const 金第3IsValid = writable(false);
